/**
* Confluent Schema Registry
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * SchemaString.h
 *
 * Schema definition
 */

#ifndef SchemaString_H_
#define SchemaString_H_


#include "SchemaReference.h"
#include <string>
#include "Metadata.h"
#include "SchemaTags.h"
#include "RuleSet.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// Schema definition
/// </summary>
class  SchemaString
{
public:
    SchemaString();
    virtual ~SchemaString() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const SchemaString& rhs) const;
    bool operator!=(const SchemaString& rhs) const;

    /////////////////////////////////////////////
    /// SchemaString members

    /// <summary>
    /// Schema type
    /// </summary>
    std::string getSchemaType() const;
    void setSchemaType(std::string const& value);
    bool schemaTypeIsSet() const;
    void unsetSchemaType();
    /// <summary>
    /// Schema string identified by the ID
    /// </summary>
    std::string getSchema() const;
    void setSchema(std::string const& value);
    bool schemaIsSet() const;
    void unsetSchema();
    /// <summary>
    /// References to other schemas
    /// </summary>
    std::vector<org::openapitools::server::model::SchemaReference> getReferences() const;
    void setReferences(std::vector<org::openapitools::server::model::SchemaReference> const& value);
    bool referencesIsSet() const;
    void unsetReferences();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::Metadata getMetadata() const;
    void setMetadata(org::openapitools::server::model::Metadata const& value);
    bool metadataIsSet() const;
    void unsetMetadata();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::RuleSet getRuleSet() const;
    void setRuleSet(org::openapitools::server::model::RuleSet const& value);
    bool ruleSetIsSet() const;
    void unsetRuleSet();
    /// <summary>
    /// Schema tags
    /// </summary>
    std::vector<org::openapitools::server::model::SchemaTags> getSchemaTags() const;
    void setSchemaTags(std::vector<org::openapitools::server::model::SchemaTags> const& value);
    bool schemaTagsIsSet() const;
    void unsetSchemaTags();
    /// <summary>
    /// Maximum ID
    /// </summary>
    int32_t getMaxId() const;
    void setMaxId(int32_t const value);
    bool maxIdIsSet() const;
    void unsetMaxId();

    friend  void to_json(nlohmann::json& j, const SchemaString& o);
    friend  void from_json(const nlohmann::json& j, SchemaString& o);
protected:
    std::string m_SchemaType;
    bool m_SchemaTypeIsSet;
    std::string m_Schema;
    bool m_SchemaIsSet;
    std::vector<org::openapitools::server::model::SchemaReference> m_References;
    bool m_ReferencesIsSet;
    org::openapitools::server::model::Metadata m_Metadata;
    bool m_MetadataIsSet;
    org::openapitools::server::model::RuleSet m_RuleSet;
    bool m_RuleSetIsSet;
    std::vector<org::openapitools::server::model::SchemaTags> m_SchemaTags;
    bool m_SchemaTagsIsSet;
    int32_t m_MaxId;
    bool m_MaxIdIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* SchemaString_H_ */
