/**
* Confluent Schema Registry
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "srclient/rest/model/Config.h"
#include "srclient/rest/model/Helpers.h"

#include <sstream>

namespace srclient::rest::model
{

Config::Config()
{
    m_Alias = "";
    m_AliasIsSet = false;
    m_Normalize = false;
    m_NormalizeIsSet = false;
    m_ValidateFields = false;
    m_ValidateFieldsIsSet = false;
    m_ValidateRules = false;
    m_ValidateRulesIsSet = false;
    m_CompatibilityLevel = "";
    m_CompatibilityLevelIsSet = false;
    m_CompatibilityGroup = "";
    m_CompatibilityGroupIsSet = false;
    m_DefaultMetadataIsSet = false;
    m_OverrideMetadataIsSet = false;
    m_DefaultRuleSetIsSet = false;
    m_OverrideRuleSetIsSet = false;
    
}

void Config::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw srclient::rest::model::ValidationException(msg.str());
    }
}

bool Config::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool Config::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "Config" : pathPrefix;

                                            
    return success;
}

bool Config::operator==(const Config& rhs) const
{
    return
    
    
    
    ((!aliasIsSet() && !rhs.aliasIsSet()) || (aliasIsSet() && rhs.aliasIsSet() && getAlias() == rhs.getAlias())) &&
    
    
    ((!normalizeIsSet() && !rhs.normalizeIsSet()) || (normalizeIsSet() && rhs.normalizeIsSet() && isNormalize() == rhs.isNormalize())) &&
    
    
    ((!validateFieldsIsSet() && !rhs.validateFieldsIsSet()) || (validateFieldsIsSet() && rhs.validateFieldsIsSet() && isValidateFields() == rhs.isValidateFields())) &&
    
    
    ((!validateRulesIsSet() && !rhs.validateRulesIsSet()) || (validateRulesIsSet() && rhs.validateRulesIsSet() && isValidateRules() == rhs.isValidateRules())) &&
    
    
    ((!compatibilityLevelIsSet() && !rhs.compatibilityLevelIsSet()) || (compatibilityLevelIsSet() && rhs.compatibilityLevelIsSet() && getCompatibilityLevel() == rhs.getCompatibilityLevel())) &&
    
    
    ((!compatibilityGroupIsSet() && !rhs.compatibilityGroupIsSet()) || (compatibilityGroupIsSet() && rhs.compatibilityGroupIsSet() && getCompatibilityGroup() == rhs.getCompatibilityGroup())) &&
    
    
    ((!defaultMetadataIsSet() && !rhs.defaultMetadataIsSet()) || (defaultMetadataIsSet() && rhs.defaultMetadataIsSet() && getDefaultMetadata() == rhs.getDefaultMetadata())) &&
    
    
    ((!overrideMetadataIsSet() && !rhs.overrideMetadataIsSet()) || (overrideMetadataIsSet() && rhs.overrideMetadataIsSet() && getOverrideMetadata() == rhs.getOverrideMetadata())) &&
    
    
    ((!defaultRuleSetIsSet() && !rhs.defaultRuleSetIsSet()) || (defaultRuleSetIsSet() && rhs.defaultRuleSetIsSet() && getDefaultRuleSet() == rhs.getDefaultRuleSet())) &&
    
    
    ((!overrideRuleSetIsSet() && !rhs.overrideRuleSetIsSet()) || (overrideRuleSetIsSet() && rhs.overrideRuleSetIsSet() && getOverrideRuleSet() == rhs.getOverrideRuleSet()))
    
    ;
}

bool Config::operator!=(const Config& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Config& o)
{
    j = nlohmann::json::object();
    if(o.aliasIsSet())
        j["alias"] = o.m_Alias;
    if(o.normalizeIsSet())
        j["normalize"] = o.m_Normalize;
    if(o.validateFieldsIsSet())
        j["validateFields"] = o.m_ValidateFields;
    if(o.validateRulesIsSet())
        j["validateRules"] = o.m_ValidateRules;
    if(o.compatibilityLevelIsSet())
        j["compatibilityLevel"] = o.m_CompatibilityLevel;
    if(o.compatibilityGroupIsSet())
        j["compatibilityGroup"] = o.m_CompatibilityGroup;
    if(o.defaultMetadataIsSet())
        j["defaultMetadata"] = o.m_DefaultMetadata;
    if(o.overrideMetadataIsSet())
        j["overrideMetadata"] = o.m_OverrideMetadata;
    if(o.defaultRuleSetIsSet())
        j["defaultRuleSet"] = o.m_DefaultRuleSet;
    if(o.overrideRuleSetIsSet())
        j["overrideRuleSet"] = o.m_OverrideRuleSet;
    
}

void from_json(const nlohmann::json& j, Config& o)
{
    if(j.find("alias") != j.end())
    {
        j.at("alias").get_to(o.m_Alias);
        o.m_AliasIsSet = true;
    } 
    if(j.find("normalize") != j.end())
    {
        j.at("normalize").get_to(o.m_Normalize);
        o.m_NormalizeIsSet = true;
    } 
    if(j.find("validateFields") != j.end())
    {
        j.at("validateFields").get_to(o.m_ValidateFields);
        o.m_ValidateFieldsIsSet = true;
    } 
    if(j.find("validateRules") != j.end())
    {
        j.at("validateRules").get_to(o.m_ValidateRules);
        o.m_ValidateRulesIsSet = true;
    } 
    if(j.find("compatibilityLevel") != j.end())
    {
        j.at("compatibilityLevel").get_to(o.m_CompatibilityLevel);
        o.m_CompatibilityLevelIsSet = true;
    } 
    if(j.find("compatibilityGroup") != j.end())
    {
        j.at("compatibilityGroup").get_to(o.m_CompatibilityGroup);
        o.m_CompatibilityGroupIsSet = true;
    } 
    if(j.find("defaultMetadata") != j.end())
    {
        j.at("defaultMetadata").get_to(o.m_DefaultMetadata);
        o.m_DefaultMetadataIsSet = true;
    } 
    if(j.find("overrideMetadata") != j.end())
    {
        j.at("overrideMetadata").get_to(o.m_OverrideMetadata);
        o.m_OverrideMetadataIsSet = true;
    } 
    if(j.find("defaultRuleSet") != j.end())
    {
        j.at("defaultRuleSet").get_to(o.m_DefaultRuleSet);
        o.m_DefaultRuleSetIsSet = true;
    } 
    if(j.find("overrideRuleSet") != j.end())
    {
        j.at("overrideRuleSet").get_to(o.m_OverrideRuleSet);
        o.m_OverrideRuleSetIsSet = true;
    } 
    
}

std::string Config::getAlias() const
{
    return m_Alias;
}
void Config::setAlias(std::string const& value)
{
    m_Alias = value;
    m_AliasIsSet = true;
}
bool Config::aliasIsSet() const
{
    return m_AliasIsSet;
}
void Config::unsetAlias()
{
    m_AliasIsSet = false;
}
bool Config::isNormalize() const
{
    return m_Normalize;
}
void Config::setNormalize(bool const value)
{
    m_Normalize = value;
    m_NormalizeIsSet = true;
}
bool Config::normalizeIsSet() const
{
    return m_NormalizeIsSet;
}
void Config::unsetNormalize()
{
    m_NormalizeIsSet = false;
}
bool Config::isValidateFields() const
{
    return m_ValidateFields;
}
void Config::setValidateFields(bool const value)
{
    m_ValidateFields = value;
    m_ValidateFieldsIsSet = true;
}
bool Config::validateFieldsIsSet() const
{
    return m_ValidateFieldsIsSet;
}
void Config::unsetValidateFields()
{
    m_ValidateFieldsIsSet = false;
}
bool Config::isValidateRules() const
{
    return m_ValidateRules;
}
void Config::setValidateRules(bool const value)
{
    m_ValidateRules = value;
    m_ValidateRulesIsSet = true;
}
bool Config::validateRulesIsSet() const
{
    return m_ValidateRulesIsSet;
}
void Config::unsetValidateRules()
{
    m_ValidateRulesIsSet = false;
}
std::string Config::getCompatibilityLevel() const
{
    return m_CompatibilityLevel;
}
void Config::setCompatibilityLevel(std::string const& value)
{
    m_CompatibilityLevel = value;
    m_CompatibilityLevelIsSet = true;
}
bool Config::compatibilityLevelIsSet() const
{
    return m_CompatibilityLevelIsSet;
}
void Config::unsetCompatibilityLevel()
{
    m_CompatibilityLevelIsSet = false;
}
std::string Config::getCompatibilityGroup() const
{
    return m_CompatibilityGroup;
}
void Config::setCompatibilityGroup(std::string const& value)
{
    m_CompatibilityGroup = value;
    m_CompatibilityGroupIsSet = true;
}
bool Config::compatibilityGroupIsSet() const
{
    return m_CompatibilityGroupIsSet;
}
void Config::unsetCompatibilityGroup()
{
    m_CompatibilityGroupIsSet = false;
}
srclient::rest::model::Metadata Config::getDefaultMetadata() const
{
    return m_DefaultMetadata;
}
void Config::setDefaultMetadata(srclient::rest::model::Metadata const& value)
{
    m_DefaultMetadata = value;
    m_DefaultMetadataIsSet = true;
}
bool Config::defaultMetadataIsSet() const
{
    return m_DefaultMetadataIsSet;
}
void Config::unsetDefaultMetadata()
{
    m_DefaultMetadataIsSet = false;
}
srclient::rest::model::Metadata Config::getOverrideMetadata() const
{
    return m_OverrideMetadata;
}
void Config::setOverrideMetadata(srclient::rest::model::Metadata const& value)
{
    m_OverrideMetadata = value;
    m_OverrideMetadataIsSet = true;
}
bool Config::overrideMetadataIsSet() const
{
    return m_OverrideMetadataIsSet;
}
void Config::unsetOverrideMetadata()
{
    m_OverrideMetadataIsSet = false;
}
srclient::rest::model::RuleSet Config::getDefaultRuleSet() const
{
    return m_DefaultRuleSet;
}
void Config::setDefaultRuleSet(srclient::rest::model::RuleSet const& value)
{
    m_DefaultRuleSet = value;
    m_DefaultRuleSetIsSet = true;
}
bool Config::defaultRuleSetIsSet() const
{
    return m_DefaultRuleSetIsSet;
}
void Config::unsetDefaultRuleSet()
{
    m_DefaultRuleSetIsSet = false;
}
srclient::rest::model::RuleSet Config::getOverrideRuleSet() const
{
    return m_OverrideRuleSet;
}
void Config::setOverrideRuleSet(srclient::rest::model::RuleSet const& value)
{
    m_OverrideRuleSet = value;
    m_OverrideRuleSetIsSet = true;
}
bool Config::overrideRuleSetIsSet() const
{
    return m_OverrideRuleSetIsSet;
}
void Config::unsetOverrideRuleSet()
{
    m_OverrideRuleSetIsSet = false;
}


} // namespace srclient::rest::model

