/**
* Confluent Schema Registry
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "srclient/rest/model/Metadata.h"

#include <sstream>

namespace srclient::rest::model
{

Metadata::Metadata()
{
    // Optional members are initialized to std::nullopt by default
}

bool Metadata::operator==(const Metadata& rhs) const
{
    return
        m_Tags == rhs.m_Tags &&
        m_Properties == rhs.m_Properties &&
        m_Sensitive == rhs.m_Sensitive;
}

bool Metadata::operator!=(const Metadata& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Metadata& o)
{
    j = nlohmann::json::object();
    if(o.m_Tags.has_value())
        j["tags"] = o.m_Tags.value();
    if(o.m_Properties.has_value())
        j["properties"] = o.m_Properties.value();
    if(o.m_Sensitive.has_value())
        j["sensitive"] = o.m_Sensitive.value();
}

void from_json(const nlohmann::json& j, Metadata& o)
{
    if(j.find("tags") != j.end())
    {
        std::map<std::string, std::set<std::string>> temp;
        j.at("tags").get_to(temp);
        o.m_Tags = temp;
    } 
    if(j.find("properties") != j.end())
    {
        std::map<std::string, std::string> temp;
        j.at("properties").get_to(temp);
        o.m_Properties = temp;
    } 
    if(j.find("sensitive") != j.end())
    {
        std::set<std::string> temp;
        j.at("sensitive").get_to(temp);
        o.m_Sensitive = temp;
    } 
}

std::optional<std::map<std::string, std::set<std::string>>> Metadata::getTags() const
{
    return m_Tags;
}

void Metadata::setTags(const std::optional<std::map<std::string, std::set<std::string>>>& value)
{
    m_Tags = value;
}

std::optional<std::map<std::string, std::string>> Metadata::getProperties() const
{
    return m_Properties;
}

void Metadata::setProperties(const std::optional<std::map<std::string, std::string>>& value)
{
    m_Properties = value;
}

std::optional<std::set<std::string>> Metadata::getSensitive() const
{
    return m_Sensitive;
}

void Metadata::setSensitive(const std::optional<std::set<std::string>>& value)
{
    m_Sensitive = value;
}

} // namespace srclient::rest::model

