/**
* Confluent Schema Registry
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "srclient/rest/model/RuleSet.h"
#include "srclient/rest/model/Helpers.h"

#include <sstream>

namespace srclient::rest::model
{

RuleSet::RuleSet()
{
    // Optional members are initialized to std::nullopt by default
}

void RuleSet::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw srclient::rest::model::ValidationException(msg.str());
    }
}

bool RuleSet::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool RuleSet::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "RuleSet" : pathPrefix;

    if (m_MigrationRules.has_value())
    {
        const std::vector<srclient::rest::model::Rule>& value = m_MigrationRules.value();
        const std::string currentValuePath = _pathPrefix + ".migrationRules";
        
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const srclient::rest::model::Rule& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                success = value.validate(msg, currentValuePath + ".migrationRules") && success;
                i++;
            }
        }
    }
    
    if (m_DomainRules.has_value())
    {
        const std::vector<srclient::rest::model::Rule>& value = m_DomainRules.value();
        const std::string currentValuePath = _pathPrefix + ".domainRules";
        
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const srclient::rest::model::Rule& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                success = value.validate(msg, currentValuePath + ".domainRules") && success;
                i++;
            }
        }
    }
    
    return success;
}

bool RuleSet::operator==(const RuleSet& rhs) const
{
    return
        m_MigrationRules == rhs.m_MigrationRules &&
        m_DomainRules == rhs.m_DomainRules &&
        m_Empty == rhs.m_Empty;
}

bool RuleSet::operator!=(const RuleSet& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const RuleSet& o)
{
    j = nlohmann::json::object();
    if(o.m_MigrationRules.has_value())
        j["migrationRules"] = o.m_MigrationRules.value();
    if(o.m_DomainRules.has_value())
        j["domainRules"] = o.m_DomainRules.value();
    if(o.m_Empty.has_value())
        j["empty"] = o.m_Empty.value();
}

void from_json(const nlohmann::json& j, RuleSet& o)
{
    if(j.find("migrationRules") != j.end())
    {
        std::vector<srclient::rest::model::Rule> temp;
        j.at("migrationRules").get_to(temp);
        o.m_MigrationRules = temp;
    } 
    if(j.find("domainRules") != j.end())
    {
        std::vector<srclient::rest::model::Rule> temp;
        j.at("domainRules").get_to(temp);
        o.m_DomainRules = temp;
    } 
    if(j.find("empty") != j.end())
    {
        bool temp;
        j.at("empty").get_to(temp);
        o.m_Empty = temp;
    } 
}

std::optional<std::vector<srclient::rest::model::Rule>> RuleSet::getMigrationRules() const
{
    return m_MigrationRules;
}

void RuleSet::setMigrationRules(const std::optional<std::vector<srclient::rest::model::Rule>>& value)
{
    m_MigrationRules = value;
}

std::optional<std::vector<srclient::rest::model::Rule>> RuleSet::getDomainRules() const
{
    return m_DomainRules;
}

void RuleSet::setDomainRules(const std::optional<std::vector<srclient::rest::model::Rule>>& value)
{
    m_DomainRules = value;
}

std::optional<bool> RuleSet::isEmpty() const
{
    return m_Empty;
}

void RuleSet::setEmpty(const std::optional<bool>& value)
{
    m_Empty = value;
}

} // namespace srclient::rest::model

