/**
* Confluent Schema Registry
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "srclient/rest/model/Schema.h"
#include "srclient/rest/model/Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

Schema::Schema()
{
    m_Subject = "";
    m_SubjectIsSet = false;
    m_Version = 0;
    m_VersionIsSet = false;
    m_Id = 0;
    m_IdIsSet = false;
    m_SchemaType = "";
    m_SchemaTypeIsSet = false;
    m_ReferencesIsSet = false;
    m_MetadataIsSet = false;
    m_RulesetIsSet = false;
    m_Schema = "";
    m_SchemaIsSet = false;
    m_SchemaTagsIsSet = false;
    m_RuleSetIsSet = false;
    
}

void Schema::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool Schema::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool Schema::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "Schema" : pathPrefix;

                         
    if (referencesIsSet())
    {
        const std::vector<org::openapitools::server::model::SchemaReference>& value = m_References;
        const std::string currentValuePath = _pathPrefix + ".references";
                
        
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const org::openapitools::server::model::SchemaReference& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".references") && success;
 
                i++;
            }
        }

    }
                     
    if (schemaTagsIsSet())
    {
        const std::vector<org::openapitools::server::model::SchemaTags>& value = m_SchemaTags;
        const std::string currentValuePath = _pathPrefix + ".schemaTags";
                
        
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const org::openapitools::server::model::SchemaTags& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".schemaTags") && success;
 
                i++;
            }
        }

    }
        
    return success;
}

bool Schema::operator==(const Schema& rhs) const
{
    return
    
    
    
    ((!subjectIsSet() && !rhs.subjectIsSet()) || (subjectIsSet() && rhs.subjectIsSet() && getSubject() == rhs.getSubject())) &&
    
    
    ((!versionIsSet() && !rhs.versionIsSet()) || (versionIsSet() && rhs.versionIsSet() && getVersion() == rhs.getVersion())) &&
    
    
    ((!idIsSet() && !rhs.idIsSet()) || (idIsSet() && rhs.idIsSet() && getId() == rhs.getId())) &&
    
    
    ((!schemaTypeIsSet() && !rhs.schemaTypeIsSet()) || (schemaTypeIsSet() && rhs.schemaTypeIsSet() && getSchemaType() == rhs.getSchemaType())) &&
    
    
    ((!referencesIsSet() && !rhs.referencesIsSet()) || (referencesIsSet() && rhs.referencesIsSet() && getReferences() == rhs.getReferences())) &&
    
    
    ((!metadataIsSet() && !rhs.metadataIsSet()) || (metadataIsSet() && rhs.metadataIsSet() && getMetadata() == rhs.getMetadata())) &&
    
    
    ((!rulesetIsSet() && !rhs.rulesetIsSet()) || (rulesetIsSet() && rhs.rulesetIsSet() && getRuleset() == rhs.getRuleset())) &&
    
    
    ((!schemaIsSet() && !rhs.schemaIsSet()) || (schemaIsSet() && rhs.schemaIsSet() && getSchema() == rhs.getSchema())) &&
    
    
    ((!schemaTagsIsSet() && !rhs.schemaTagsIsSet()) || (schemaTagsIsSet() && rhs.schemaTagsIsSet() && getSchemaTags() == rhs.getSchemaTags())) &&
    
    
    ((!ruleSetIsSet() && !rhs.ruleSetIsSet()) || (ruleSetIsSet() && rhs.ruleSetIsSet() && getRuleSet() == rhs.getRuleSet()))
    
    ;
}

bool Schema::operator!=(const Schema& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const Schema& o)
{
    j = nlohmann::json::object();
    if(o.subjectIsSet())
        j["subject"] = o.m_Subject;
    if(o.versionIsSet())
        j["version"] = o.m_Version;
    if(o.idIsSet())
        j["id"] = o.m_Id;
    if(o.schemaTypeIsSet())
        j["schemaType"] = o.m_SchemaType;
    if(o.referencesIsSet() || !o.m_References.empty())
        j["references"] = o.m_References;
    if(o.metadataIsSet())
        j["metadata"] = o.m_Metadata;
    if(o.rulesetIsSet())
        j["ruleset"] = o.m_Ruleset;
    if(o.schemaIsSet())
        j["schema"] = o.m_Schema;
    if(o.schemaTagsIsSet() || !o.m_SchemaTags.empty())
        j["schemaTags"] = o.m_SchemaTags;
    if(o.ruleSetIsSet())
        j["ruleSet"] = o.m_RuleSet;
    
}

void from_json(const nlohmann::json& j, Schema& o)
{
    if(j.find("subject") != j.end())
    {
        j.at("subject").get_to(o.m_Subject);
        o.m_SubjectIsSet = true;
    } 
    if(j.find("version") != j.end())
    {
        j.at("version").get_to(o.m_Version);
        o.m_VersionIsSet = true;
    } 
    if(j.find("id") != j.end())
    {
        j.at("id").get_to(o.m_Id);
        o.m_IdIsSet = true;
    } 
    if(j.find("schemaType") != j.end())
    {
        j.at("schemaType").get_to(o.m_SchemaType);
        o.m_SchemaTypeIsSet = true;
    } 
    if(j.find("references") != j.end())
    {
        j.at("references").get_to(o.m_References);
        o.m_ReferencesIsSet = true;
    } 
    if(j.find("metadata") != j.end())
    {
        j.at("metadata").get_to(o.m_Metadata);
        o.m_MetadataIsSet = true;
    } 
    if(j.find("ruleset") != j.end())
    {
        j.at("ruleset").get_to(o.m_Ruleset);
        o.m_RulesetIsSet = true;
    } 
    if(j.find("schema") != j.end())
    {
        j.at("schema").get_to(o.m_Schema);
        o.m_SchemaIsSet = true;
    } 
    if(j.find("schemaTags") != j.end())
    {
        j.at("schemaTags").get_to(o.m_SchemaTags);
        o.m_SchemaTagsIsSet = true;
    } 
    if(j.find("ruleSet") != j.end())
    {
        j.at("ruleSet").get_to(o.m_RuleSet);
        o.m_RuleSetIsSet = true;
    } 
    
}

std::string Schema::getSubject() const
{
    return m_Subject;
}
void Schema::setSubject(std::string const& value)
{
    m_Subject = value;
    m_SubjectIsSet = true;
}
bool Schema::subjectIsSet() const
{
    return m_SubjectIsSet;
}
void Schema::unsetSubject()
{
    m_SubjectIsSet = false;
}
int32_t Schema::getVersion() const
{
    return m_Version;
}
void Schema::setVersion(int32_t const value)
{
    m_Version = value;
    m_VersionIsSet = true;
}
bool Schema::versionIsSet() const
{
    return m_VersionIsSet;
}
void Schema::unsetVersion()
{
    m_VersionIsSet = false;
}
int32_t Schema::getId() const
{
    return m_Id;
}
void Schema::setId(int32_t const value)
{
    m_Id = value;
    m_IdIsSet = true;
}
bool Schema::idIsSet() const
{
    return m_IdIsSet;
}
void Schema::unsetId()
{
    m_IdIsSet = false;
}
std::string Schema::getSchemaType() const
{
    return m_SchemaType;
}
void Schema::setSchemaType(std::string const& value)
{
    m_SchemaType = value;
    m_SchemaTypeIsSet = true;
}
bool Schema::schemaTypeIsSet() const
{
    return m_SchemaTypeIsSet;
}
void Schema::unsetSchemaType()
{
    m_SchemaTypeIsSet = false;
}
std::vector<org::openapitools::server::model::SchemaReference> Schema::getReferences() const
{
    return m_References;
}
void Schema::setReferences(std::vector<org::openapitools::server::model::SchemaReference> const& value)
{
    m_References = value;
    m_ReferencesIsSet = true;
}
bool Schema::referencesIsSet() const
{
    return m_ReferencesIsSet;
}
void Schema::unsetReferences()
{
    m_ReferencesIsSet = false;
}
org::openapitools::server::model::Metadata Schema::getMetadata() const
{
    return m_Metadata;
}
void Schema::setMetadata(org::openapitools::server::model::Metadata const& value)
{
    m_Metadata = value;
    m_MetadataIsSet = true;
}
bool Schema::metadataIsSet() const
{
    return m_MetadataIsSet;
}
void Schema::unsetMetadata()
{
    m_MetadataIsSet = false;
}
org::openapitools::server::model::RuleSet Schema::getRuleset() const
{
    return m_Ruleset;
}
void Schema::setRuleset(org::openapitools::server::model::RuleSet const& value)
{
    m_Ruleset = value;
    m_RulesetIsSet = true;
}
bool Schema::rulesetIsSet() const
{
    return m_RulesetIsSet;
}
void Schema::unsetRuleset()
{
    m_RulesetIsSet = false;
}
std::string Schema::getSchema() const
{
    return m_Schema;
}
void Schema::setSchema(std::string const& value)
{
    m_Schema = value;
    m_SchemaIsSet = true;
}
bool Schema::schemaIsSet() const
{
    return m_SchemaIsSet;
}
void Schema::unsetSchema()
{
    m_SchemaIsSet = false;
}
std::vector<org::openapitools::server::model::SchemaTags> Schema::getSchemaTags() const
{
    return m_SchemaTags;
}
void Schema::setSchemaTags(std::vector<org::openapitools::server::model::SchemaTags> const& value)
{
    m_SchemaTags = value;
    m_SchemaTagsIsSet = true;
}
bool Schema::schemaTagsIsSet() const
{
    return m_SchemaTagsIsSet;
}
void Schema::unsetSchemaTags()
{
    m_SchemaTagsIsSet = false;
}
org::openapitools::server::model::RuleSet Schema::getRuleSet() const
{
    return m_RuleSet;
}
void Schema::setRuleSet(org::openapitools::server::model::RuleSet const& value)
{
    m_RuleSet = value;
    m_RuleSetIsSet = true;
}
bool Schema::ruleSetIsSet() const
{
    return m_RuleSetIsSet;
}
void Schema::unsetRuleSet()
{
    m_RuleSetIsSet = false;
}


} // namespace org::openapitools::server::model

