/**
* Confluent Schema Registry
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "srclient/rest/model/SchemaString.h"
#include "srclient/rest/model/Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

SchemaString::SchemaString()
{
    m_SchemaType = "";
    m_SchemaTypeIsSet = false;
    m_Schema = "";
    m_SchemaIsSet = false;
    m_ReferencesIsSet = false;
    m_MetadataIsSet = false;
    m_RuleSetIsSet = false;
    m_SchemaTagsIsSet = false;
    m_MaxId = 0;
    m_MaxIdIsSet = false;
    
}

void SchemaString::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool SchemaString::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool SchemaString::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "SchemaString" : pathPrefix;

                 
    if (referencesIsSet())
    {
        const std::vector<org::openapitools::server::model::SchemaReference>& value = m_References;
        const std::string currentValuePath = _pathPrefix + ".references";
                
        
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const org::openapitools::server::model::SchemaReference& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".references") && success;
 
                i++;
            }
        }

    }
                 
    if (schemaTagsIsSet())
    {
        const std::vector<org::openapitools::server::model::SchemaTags>& value = m_SchemaTags;
        const std::string currentValuePath = _pathPrefix + ".schemaTags";
                
        
        { // Recursive validation of array elements
            const std::string oldValuePath = currentValuePath;
            int i = 0;
            for (const org::openapitools::server::model::SchemaTags& value : value)
            { 
                const std::string currentValuePath = oldValuePath + "[" + std::to_string(i) + "]";
                        
        success = value.validate(msg, currentValuePath + ".schemaTags") && success;
 
                i++;
            }
        }

    }
        
    return success;
}

bool SchemaString::operator==(const SchemaString& rhs) const
{
    return
    
    
    
    ((!schemaTypeIsSet() && !rhs.schemaTypeIsSet()) || (schemaTypeIsSet() && rhs.schemaTypeIsSet() && getSchemaType() == rhs.getSchemaType())) &&
    
    
    ((!schemaIsSet() && !rhs.schemaIsSet()) || (schemaIsSet() && rhs.schemaIsSet() && getSchema() == rhs.getSchema())) &&
    
    
    ((!referencesIsSet() && !rhs.referencesIsSet()) || (referencesIsSet() && rhs.referencesIsSet() && getReferences() == rhs.getReferences())) &&
    
    
    ((!metadataIsSet() && !rhs.metadataIsSet()) || (metadataIsSet() && rhs.metadataIsSet() && getMetadata() == rhs.getMetadata())) &&
    
    
    ((!ruleSetIsSet() && !rhs.ruleSetIsSet()) || (ruleSetIsSet() && rhs.ruleSetIsSet() && getRuleSet() == rhs.getRuleSet())) &&
    
    
    ((!schemaTagsIsSet() && !rhs.schemaTagsIsSet()) || (schemaTagsIsSet() && rhs.schemaTagsIsSet() && getSchemaTags() == rhs.getSchemaTags())) &&
    
    
    ((!maxIdIsSet() && !rhs.maxIdIsSet()) || (maxIdIsSet() && rhs.maxIdIsSet() && getMaxId() == rhs.getMaxId()))
    
    ;
}

bool SchemaString::operator!=(const SchemaString& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const SchemaString& o)
{
    j = nlohmann::json::object();
    if(o.schemaTypeIsSet())
        j["schemaType"] = o.m_SchemaType;
    if(o.schemaIsSet())
        j["schema"] = o.m_Schema;
    if(o.referencesIsSet() || !o.m_References.empty())
        j["references"] = o.m_References;
    if(o.metadataIsSet())
        j["metadata"] = o.m_Metadata;
    if(o.ruleSetIsSet())
        j["ruleSet"] = o.m_RuleSet;
    if(o.schemaTagsIsSet() || !o.m_SchemaTags.empty())
        j["schemaTags"] = o.m_SchemaTags;
    if(o.maxIdIsSet())
        j["maxId"] = o.m_MaxId;
    
}

void from_json(const nlohmann::json& j, SchemaString& o)
{
    if(j.find("schemaType") != j.end())
    {
        j.at("schemaType").get_to(o.m_SchemaType);
        o.m_SchemaTypeIsSet = true;
    } 
    if(j.find("schema") != j.end())
    {
        j.at("schema").get_to(o.m_Schema);
        o.m_SchemaIsSet = true;
    } 
    if(j.find("references") != j.end())
    {
        j.at("references").get_to(o.m_References);
        o.m_ReferencesIsSet = true;
    } 
    if(j.find("metadata") != j.end())
    {
        j.at("metadata").get_to(o.m_Metadata);
        o.m_MetadataIsSet = true;
    } 
    if(j.find("ruleSet") != j.end())
    {
        j.at("ruleSet").get_to(o.m_RuleSet);
        o.m_RuleSetIsSet = true;
    } 
    if(j.find("schemaTags") != j.end())
    {
        j.at("schemaTags").get_to(o.m_SchemaTags);
        o.m_SchemaTagsIsSet = true;
    } 
    if(j.find("maxId") != j.end())
    {
        j.at("maxId").get_to(o.m_MaxId);
        o.m_MaxIdIsSet = true;
    } 
    
}

std::string SchemaString::getSchemaType() const
{
    return m_SchemaType;
}
void SchemaString::setSchemaType(std::string const& value)
{
    m_SchemaType = value;
    m_SchemaTypeIsSet = true;
}
bool SchemaString::schemaTypeIsSet() const
{
    return m_SchemaTypeIsSet;
}
void SchemaString::unsetSchemaType()
{
    m_SchemaTypeIsSet = false;
}
std::string SchemaString::getSchema() const
{
    return m_Schema;
}
void SchemaString::setSchema(std::string const& value)
{
    m_Schema = value;
    m_SchemaIsSet = true;
}
bool SchemaString::schemaIsSet() const
{
    return m_SchemaIsSet;
}
void SchemaString::unsetSchema()
{
    m_SchemaIsSet = false;
}
std::vector<org::openapitools::server::model::SchemaReference> SchemaString::getReferences() const
{
    return m_References;
}
void SchemaString::setReferences(std::vector<org::openapitools::server::model::SchemaReference> const& value)
{
    m_References = value;
    m_ReferencesIsSet = true;
}
bool SchemaString::referencesIsSet() const
{
    return m_ReferencesIsSet;
}
void SchemaString::unsetReferences()
{
    m_ReferencesIsSet = false;
}
org::openapitools::server::model::Metadata SchemaString::getMetadata() const
{
    return m_Metadata;
}
void SchemaString::setMetadata(org::openapitools::server::model::Metadata const& value)
{
    m_Metadata = value;
    m_MetadataIsSet = true;
}
bool SchemaString::metadataIsSet() const
{
    return m_MetadataIsSet;
}
void SchemaString::unsetMetadata()
{
    m_MetadataIsSet = false;
}
org::openapitools::server::model::RuleSet SchemaString::getRuleSet() const
{
    return m_RuleSet;
}
void SchemaString::setRuleSet(org::openapitools::server::model::RuleSet const& value)
{
    m_RuleSet = value;
    m_RuleSetIsSet = true;
}
bool SchemaString::ruleSetIsSet() const
{
    return m_RuleSetIsSet;
}
void SchemaString::unsetRuleSet()
{
    m_RuleSetIsSet = false;
}
std::vector<org::openapitools::server::model::SchemaTags> SchemaString::getSchemaTags() const
{
    return m_SchemaTags;
}
void SchemaString::setSchemaTags(std::vector<org::openapitools::server::model::SchemaTags> const& value)
{
    m_SchemaTags = value;
    m_SchemaTagsIsSet = true;
}
bool SchemaString::schemaTagsIsSet() const
{
    return m_SchemaTagsIsSet;
}
void SchemaString::unsetSchemaTags()
{
    m_SchemaTagsIsSet = false;
}
int32_t SchemaString::getMaxId() const
{
    return m_MaxId;
}
void SchemaString::setMaxId(int32_t const value)
{
    m_MaxId = value;
    m_MaxIdIsSet = true;
}
bool SchemaString::maxIdIsSet() const
{
    return m_MaxIdIsSet;
}
void SchemaString::unsetMaxId()
{
    m_MaxIdIsSet = false;
}


} // namespace org::openapitools::server::model

