/**
* Confluent Schema Registry
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#include "srclient/rest/model/SchemaReference.h"
#include "srclient/rest/model/Helpers.h"

#include <sstream>

namespace org::openapitools::server::model
{

SchemaReference::SchemaReference()
{
    m_Name = "";
    m_NameIsSet = false;
    m_Subject = "";
    m_SubjectIsSet = false;
    m_Version = 0;
    m_VersionIsSet = false;
    
}

void SchemaReference::validate() const
{
    std::stringstream msg;
    if (!validate(msg))
    {
        throw org::openapitools::server::helpers::ValidationException(msg.str());
    }
}

bool SchemaReference::validate(std::stringstream& msg) const
{
    return validate(msg, "");
}

bool SchemaReference::validate(std::stringstream& msg, const std::string& pathPrefix) const
{
    bool success = true;
    const std::string _pathPrefix = pathPrefix.empty() ? "SchemaReference" : pathPrefix;

                
    return success;
}

bool SchemaReference::operator==(const SchemaReference& rhs) const
{
    return
    
    
    
    ((!nameIsSet() && !rhs.nameIsSet()) || (nameIsSet() && rhs.nameIsSet() && getName() == rhs.getName())) &&
    
    
    ((!subjectIsSet() && !rhs.subjectIsSet()) || (subjectIsSet() && rhs.subjectIsSet() && getSubject() == rhs.getSubject())) &&
    
    
    ((!versionIsSet() && !rhs.versionIsSet()) || (versionIsSet() && rhs.versionIsSet() && getVersion() == rhs.getVersion()))
    
    ;
}

bool SchemaReference::operator!=(const SchemaReference& rhs) const
{
    return !(*this == rhs);
}

void to_json(nlohmann::json& j, const SchemaReference& o)
{
    j = nlohmann::json::object();
    if(o.nameIsSet())
        j["name"] = o.m_Name;
    if(o.subjectIsSet())
        j["subject"] = o.m_Subject;
    if(o.versionIsSet())
        j["version"] = o.m_Version;
    
}

void from_json(const nlohmann::json& j, SchemaReference& o)
{
    if(j.find("name") != j.end())
    {
        j.at("name").get_to(o.m_Name);
        o.m_NameIsSet = true;
    } 
    if(j.find("subject") != j.end())
    {
        j.at("subject").get_to(o.m_Subject);
        o.m_SubjectIsSet = true;
    } 
    if(j.find("version") != j.end())
    {
        j.at("version").get_to(o.m_Version);
        o.m_VersionIsSet = true;
    } 
    
}

std::string SchemaReference::getName() const
{
    return m_Name;
}
void SchemaReference::setName(std::string const& value)
{
    m_Name = value;
    m_NameIsSet = true;
}
bool SchemaReference::nameIsSet() const
{
    return m_NameIsSet;
}
void SchemaReference::unsetName()
{
    m_NameIsSet = false;
}
std::string SchemaReference::getSubject() const
{
    return m_Subject;
}
void SchemaReference::setSubject(std::string const& value)
{
    m_Subject = value;
    m_SubjectIsSet = true;
}
bool SchemaReference::subjectIsSet() const
{
    return m_SubjectIsSet;
}
void SchemaReference::unsetSubject()
{
    m_SubjectIsSet = false;
}
int32_t SchemaReference::getVersion() const
{
    return m_Version;
}
void SchemaReference::setVersion(int32_t const value)
{
    m_Version = value;
    m_VersionIsSet = true;
}
bool SchemaReference::versionIsSet() const
{
    return m_VersionIsSet;
}
void SchemaReference::unsetVersion()
{
    m_VersionIsSet = false;
}


} // namespace org::openapitools::server::model

