/**
* Confluent Schema Registry
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ErrorMessage.h
 *
 * Error message
 */

#ifndef ErrorMessage_H_
#define ErrorMessage_H_


#include <string>
#include <nlohmann/json.hpp>

namespace srclient::rest::model
{

/// <summary>
/// Error message
/// </summary>
class  ErrorMessage
{
public:
    ErrorMessage();
    virtual ~ErrorMessage() = default;

    bool operator==(const ErrorMessage& rhs) const;
    bool operator!=(const ErrorMessage& rhs) const;

    /////////////////////////////////////////////
    /// ErrorMessage members

    /// <summary>
    /// Error code
    /// </summary>
    int32_t getErrorCode() const;
    void setErrorCode(int32_t const value);
    bool errorCodeIsSet() const;
    void unsetError_code();
    /// <summary>
    /// Detailed error message
    /// </summary>
    std::string getMessage() const;
    void setMessage(std::string const& value);
    bool messageIsSet() const;
    void unsetMessage();

    friend  void to_json(nlohmann::json& j, const ErrorMessage& o);
    friend  void from_json(const nlohmann::json& j, ErrorMessage& o);
protected:
    int32_t m_Error_code;
    bool m_Error_codeIsSet;
    std::string m_Message;
    bool m_MessageIsSet;
    
};

} // namespace srclient::rest::model

#endif /* ErrorMessage_H_ */
