/**
* Confluent Schema Registry
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * ExtendedSchema.h
 *
 * ExtendedSchema
 */

#ifndef ExtendedSchema_H_
#define ExtendedSchema_H_


#include "SchemaReference.h"
#include <string>
#include "Metadata.h"
#include "SchemaTags.h"
#include "RuleSet.h"
#include <vector>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// ExtendedSchema
/// </summary>
class  ExtendedSchema
{
public:
    ExtendedSchema();
    virtual ~ExtendedSchema() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const ExtendedSchema& rhs) const;
    bool operator!=(const ExtendedSchema& rhs) const;

    /////////////////////////////////////////////
    /// ExtendedSchema members

    /// <summary>
    /// Name of the subject
    /// </summary>
    std::string getSubject() const;
    void setSubject(std::string const& value);
    bool subjectIsSet() const;
    void unsetSubject();
    /// <summary>
    /// Version number
    /// </summary>
    int32_t getVersion() const;
    void setVersion(int32_t const value);
    bool versionIsSet() const;
    void unsetVersion();
    /// <summary>
    /// Identifier of the schema
    /// </summary>
    int32_t getId() const;
    void setId(int32_t const value);
    bool idIsSet() const;
    void unsetId();
    /// <summary>
    /// Globally unique identifier of the schema
    /// </summary>
    std::string getGuid() const;
    void setGuid(std::string const& value);
    bool guidIsSet() const;
    void unsetGuid();
    /// <summary>
    /// Schema type
    /// </summary>
    std::string getSchemaType() const;
    void setSchemaType(std::string const& value);
    bool schemaTypeIsSet() const;
    void unsetSchemaType();
    /// <summary>
    /// References to other schemas
    /// </summary>
    std::vector<org::openapitools::server::model::SchemaReference> getReferences() const;
    void setReferences(std::vector<org::openapitools::server::model::SchemaReference> const& value);
    bool referencesIsSet() const;
    void unsetReferences();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::Metadata getMetadata() const;
    void setMetadata(org::openapitools::server::model::Metadata const& value);
    bool metadataIsSet() const;
    void unsetMetadata();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::RuleSet getRuleset() const;
    void setRuleset(org::openapitools::server::model::RuleSet const& value);
    bool rulesetIsSet() const;
    void unsetRuleset();
    /// <summary>
    /// Schema definition string
    /// </summary>
    std::string getSchema() const;
    void setSchema(std::string const& value);
    bool schemaIsSet() const;
    void unsetSchema();
    /// <summary>
    /// Aliases for the given subject
    /// </summary>
    std::vector<std::string> getAliases() const;
    void setAliases(std::vector<std::string> const& value);
    bool aliasesIsSet() const;
    void unsetAliases();
    /// <summary>
    /// 
    /// </summary>
    org::openapitools::server::model::RuleSet getRuleSet() const;
    void setRuleSet(org::openapitools::server::model::RuleSet const& value);
    bool ruleSetIsSet() const;
    void unsetRuleSet();
    /// <summary>
    /// Schema tags
    /// </summary>
    std::vector<org::openapitools::server::model::SchemaTags> getSchemaTags() const;
    void setSchemaTags(std::vector<org::openapitools::server::model::SchemaTags> const& value);
    bool schemaTagsIsSet() const;
    void unsetSchemaTags();

    friend  void to_json(nlohmann::json& j, const ExtendedSchema& o);
    friend  void from_json(const nlohmann::json& j, ExtendedSchema& o);
protected:
    std::string m_Subject;
    bool m_SubjectIsSet;
    int32_t m_Version;
    bool m_VersionIsSet;
    int32_t m_Id;
    bool m_IdIsSet;
    std::string m_Guid;
    bool m_GuidIsSet;
    std::string m_SchemaType;
    bool m_SchemaTypeIsSet;
    std::vector<org::openapitools::server::model::SchemaReference> m_References;
    bool m_ReferencesIsSet;
    org::openapitools::server::model::Metadata m_Metadata;
    bool m_MetadataIsSet;
    org::openapitools::server::model::RuleSet m_Ruleset;
    bool m_RulesetIsSet;
    std::string m_Schema;
    bool m_SchemaIsSet;
    std::vector<std::string> m_Aliases;
    bool m_AliasesIsSet;
    org::openapitools::server::model::RuleSet m_RuleSet;
    bool m_RuleSetIsSet;
    std::vector<org::openapitools::server::model::SchemaTags> m_SchemaTags;
    bool m_SchemaTagsIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* ExtendedSchema_H_ */
