/**
* Confluent Schema Registry
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Metadata.h
 *
 * User-defined metadata
 */

#ifndef Metadata_H_
#define Metadata_H_


#include <string>
#include <map>
#include <set>
#include <optional>
#include <nlohmann/json.hpp>

namespace srclient::rest::model
{

/// <summary>
/// User-defined metadata
/// </summary>
class  Metadata
{
public:
    Metadata();
    virtual ~Metadata() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const Metadata& rhs) const;
    bool operator!=(const Metadata& rhs) const;

    /////////////////////////////////////////////
    /// Metadata members

    /// <summary>
    /// 
    /// </summary>
    std::optional<std::map<std::string, std::set<std::string>>> getTags() const;
    void setTags(const std::optional<std::map<std::string, std::set<std::string>>>& value);
    /// <summary>
    /// 
    /// </summary>
    std::optional<std::map<std::string, std::string>> getProperties() const;
    void setProperties(const std::optional<std::map<std::string, std::string>>& value);
    /// <summary>
    /// 
    /// </summary>
    std::optional<std::set<std::string>> getSensitive() const;
    void setSensitive(const std::optional<std::set<std::string>>& value);

    friend  void to_json(nlohmann::json& j, const Metadata& o);
    friend  void from_json(const nlohmann::json& j, Metadata& o);
protected:
    std::optional<std::map<std::string, std::set<std::string>>> m_Tags;
    std::optional<std::map<std::string, std::string>> m_Properties;
    std::optional<std::set<std::string>> m_Sensitive;
    
};

} // namespace srclient::rest::model

#endif /* Metadata_H_ */
