/**
* Confluent Schema Registry
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * RegisteredSchema.h
 *
 * Schema register response
 */

#ifndef SRCLIENT_REST_MODEL_REGISTERED_SCHEMA_H_
#define SRCLIENT_REST_MODEL_REGISTERED_SCHEMA_H_


#include "Schema.h"
#include "SchemaReference.h"
#include <string>
#include "Metadata.h"
#include "RuleSet.h"
#include <vector>
#include <optional>
#include <nlohmann/json.hpp>

namespace srclient::rest::model
{

/// <summary>
/// Schema register response
/// </summary>
class  RegisteredSchema
{
public:
    RegisteredSchema();
    RegisteredSchema(
        const std::optional<int32_t>& id,
        const std::optional<std::string>& guid,
        const std::optional<std::string>& subject,
        const std::optional<int32_t>& version,
        const Schema& schema);

    virtual ~RegisteredSchema() = default;

    bool operator==(const RegisteredSchema& rhs) const;
    bool operator!=(const RegisteredSchema& rhs) const;

    /////////////////////////////////////////////
    /// RegisteredSchema members

    /// <summary>
    /// Identifier of the schema
    /// </summary>
    std::optional<int32_t> getId() const;
    void setId(const std::optional<int32_t>& value);
    /// <summary>
    /// Globally unique identifier of the schema
    /// </summary>
    std::optional<std::string> getGuid() const;
    void setGuid(const std::optional<std::string>& value);
    /// <summary>
    /// Subject
    /// </summary>
    std::optional<std::string> getSubject() const;
    void setSubject(const std::optional<std::string>& value);
    /// <summary>
    /// Version number
    /// </summary>
    std::optional<int32_t> getVersion() const;
    void setVersion(const std::optional<int32_t>& value);
    /// <summary>
    /// Schema type
    /// </summary>
    std::optional<std::string> getSchemaType() const;
    void setSchemaType(const std::optional<std::string>& value);
    /// <summary>
    /// References to other schemas
    /// </summary>
    std::optional<std::vector<srclient::rest::model::SchemaReference>> getReferences() const;
    void setReferences(const std::optional<std::vector<srclient::rest::model::SchemaReference>>& value);
    /// <summary>
    /// 
    /// </summary>
    std::optional<srclient::rest::model::Metadata> getMetadata() const;
    void setMetadata(const std::optional<srclient::rest::model::Metadata>& value);
    /// <summary>
    /// 
    /// </summary>
    std::optional<srclient::rest::model::RuleSet> getRuleSet() const;
    void setRuleSet(const std::optional<srclient::rest::model::RuleSet>& value);
    /// <summary>
    /// Schema definition string
    /// </summary>
    std::optional<std::string> getSchema() const;
    void setSchema(const std::optional<std::string>& value);

    srclient::rest::model::Schema toSchema() const;

    friend  void to_json(nlohmann::json& j, const RegisteredSchema& o);
    friend  void from_json(const nlohmann::json& j, RegisteredSchema& o);
protected:
    std::optional<int32_t> m_Id;
    std::optional<std::string> m_Guid;
    std::optional<std::string> m_Subject;
    std::optional<int32_t> m_Version;
    std::optional<std::string> m_SchemaType;
    std::optional<std::vector<srclient::rest::model::SchemaReference>> m_References;
    std::optional<srclient::rest::model::Metadata> m_Metadata;
    std::optional<srclient::rest::model::RuleSet> m_RuleSet;
    std::optional<std::string> m_Schema;
    
};

} // namespace srclient::rest::model

#endif /* SRCLIENT_REST_MODEL_REGISTERED_SCHEMA_H_ */
