/**
* Confluent Schema Registry
* No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
*
* The version of the OpenAPI document: v1
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
/*
 * Metadata.h
 *
 * User-defined metadata
 */

#ifndef Metadata_H_
#define Metadata_H_


#include <string>
#include <map>
#include <set>
#include <nlohmann/json.hpp>

namespace org::openapitools::server::model
{

/// <summary>
/// User-defined metadata
/// </summary>
class  Metadata
{
public:
    Metadata();
    virtual ~Metadata() = default;


    /// <summary>
    /// Validate the current data in the model. Throws a ValidationException on failure.
    /// </summary>
    void validate() const;

    /// <summary>
    /// Validate the current data in the model. Returns false on error and writes an error
    /// message into the given stringstream.
    /// </summary>
    bool validate(std::stringstream& msg) const;

    /// <summary>
    /// Helper overload for validate. Used when one model stores another model and calls it's validate.
    /// Not meant to be called outside that case.
    /// </summary>
    bool validate(std::stringstream& msg, const std::string& pathPrefix) const;

    bool operator==(const Metadata& rhs) const;
    bool operator!=(const Metadata& rhs) const;

    /////////////////////////////////////////////
    /// Metadata members

    /// <summary>
    /// 
    /// </summary>
    std::map<std::string, std::set<std::string>> getTags() const;
    void setTags(std::map<std::string, std::set<std::string>> const& value);
    bool tagsIsSet() const;
    void unsetTags();
    /// <summary>
    /// 
    /// </summary>
    std::map<std::string, std::string> getProperties() const;
    void setProperties(std::map<std::string, std::string> const& value);
    bool propertiesIsSet() const;
    void unsetProperties();
    /// <summary>
    /// 
    /// </summary>
    std::set<std::string> getSensitive() const;
    void setSensitive(std::set<std::string> const& value);
    bool sensitiveIsSet() const;
    void unsetSensitive();

    friend  void to_json(nlohmann::json& j, const Metadata& o);
    friend  void from_json(const nlohmann::json& j, Metadata& o);
protected:
    std::map<std::string, std::set<std::string>> m_Tags;
    bool m_TagsIsSet;
    std::map<std::string, std::string> m_Properties;
    bool m_PropertiesIsSet;
    std::set<std::string> m_Sensitive;
    bool m_SensitiveIsSet;
    
};

} // namespace org::openapitools::server::model

#endif /* Metadata_H_ */
