/**
 * Confluent Schema Registry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.13.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RestException.h
 *
 * This is the exception being thrown in case the api call was not successful
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_RestException_H_
#define ORG_OPENAPITOOLS_CLIENT_API_RestException_H_


#include <memory>
#include <map>

namespace srclient::rest {

class  RestException
{
public:
    RestException(const std::string_view message
        , int errorCode = 0
        , std::shared_ptr<std::istream> content = nullptr );
    virtual ~RestException();

    std::shared_ptr<std::istream> getContent() const;

protected:
    std::shared_ptr<std::istream> m_Content;
};

}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_RestBase_H_ */
