/**
 * Confluent Schema Registry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.13.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RestException.h
 *
 * This is the exception being thrown in case the api call was not successful
 */

#pragma once

#include <memory>
#include <map>
#include <stdexcept>
#include <string>

namespace srclient::rest {

class RestException : public std::runtime_error
{
public:
    RestException(const std::string_view message
        , int errorCode = 0
        , std::shared_ptr<std::istream> content = nullptr );
    virtual ~RestException();

    std::shared_ptr<std::istream> getContent() const;
    int getErrorCode() const;

protected:
    std::shared_ptr<std::istream> content_;
    std::string message_;
    int errorCode_;
};

}


