/**
 * Confluent Schema Registry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.13.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RestClient.h
 *
 * This is an API client responsible for stating the HTTP calls
 */

#ifndef SRCLIENT_REST_REST_CLIENT_H_
#define SRCLIENT_REST_REST_CLIENT_H_


#include "srclient/rest/ClientConfiguration.h"
#include "srclient/rest/RestException.h"

#if  defined (_WIN32) || defined (_WIN64)
#undef U
#endif

#include <memory>
#include <vector>
#include <functional>
#include <httplib.h>

namespace srclient::rest {

class  RestClient
{
public:
    RestClient( std::shared_ptr<const ClientConfiguration> configuration = nullptr );
    virtual ~RestClient();

    std::shared_ptr<const ClientConfiguration> getConfiguration() const;

    httplib::Result sendRequest(
            const std::string& path,
            const std::string& method,
            const httplib::Params& query,
            const httplib::Headers& headers,
            const std::string& body
    ) const;

protected:
    std::shared_ptr<const ClientConfiguration> m_Configuration;
    std::vector<std::unique_ptr<httplib::Client>> m_Clients;
};

}

#endif /* SRCLIENT_REST_REST_CLIENT_H_ */
