// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: test/dep.proto
// Protobuf C++ Version: 5.29.3

#ifndef test_2fdep_2eproto_2epb_2eh
#define test_2fdep_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "test/test.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_test_2fdep_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_test_2fdep_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_test_2fdep_2eproto;
namespace test {
class DependencyMessage;
struct DependencyMessageDefaultTypeInternal;
extern DependencyMessageDefaultTypeInternal _DependencyMessage_default_instance_;
}  // namespace test
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace test {

// ===================================================================


// -------------------------------------------------------------------

class DependencyMessage final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:test.DependencyMessage) */ {
 public:
  inline DependencyMessage() : DependencyMessage(nullptr) {}
  ~DependencyMessage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(DependencyMessage* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(DependencyMessage));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DependencyMessage(
      ::google::protobuf::internal::ConstantInitialized);

  inline DependencyMessage(const DependencyMessage& from) : DependencyMessage(nullptr, from) {}
  inline DependencyMessage(DependencyMessage&& from) noexcept
      : DependencyMessage(nullptr, std::move(from)) {}
  inline DependencyMessage& operator=(const DependencyMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline DependencyMessage& operator=(DependencyMessage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DependencyMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const DependencyMessage* internal_default_instance() {
    return reinterpret_cast<const DependencyMessage*>(
        &_DependencyMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(DependencyMessage& a, DependencyMessage& b) { a.Swap(&b); }
  inline void Swap(DependencyMessage* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DependencyMessage* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DependencyMessage* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<DependencyMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DependencyMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DependencyMessage& from) { DependencyMessage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(DependencyMessage* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "test.DependencyMessage"; }

 protected:
  explicit DependencyMessage(::google::protobuf::Arena* arena);
  DependencyMessage(::google::protobuf::Arena* arena, const DependencyMessage& from);
  DependencyMessage(::google::protobuf::Arena* arena, DependencyMessage&& from) noexcept
      : DependencyMessage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTestMessageFieldNumber = 2,
    kIsActiveFieldNumber = 1,
  };
  // .test.TestMessage test_message = 2;
  bool has_test_message() const;
  void clear_test_message() ;
  const ::test::TestMessage& test_message() const;
  PROTOBUF_NODISCARD ::test::TestMessage* release_test_message();
  ::test::TestMessage* mutable_test_message();
  void set_allocated_test_message(::test::TestMessage* value);
  void unsafe_arena_set_allocated_test_message(::test::TestMessage* value);
  ::test::TestMessage* unsafe_arena_release_test_message();

  private:
  const ::test::TestMessage& _internal_test_message() const;
  ::test::TestMessage* _internal_mutable_test_message();

  public:
  // bool is_active = 1;
  void clear_is_active() ;
  bool is_active() const;
  void set_is_active(bool value);

  private:
  bool _internal_is_active() const;
  void _internal_set_is_active(bool value);

  public:
  // @@protoc_insertion_point(class_scope:test.DependencyMessage)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const DependencyMessage& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::test::TestMessage* test_message_;
    bool is_active_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_test_2fdep_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// DependencyMessage

// bool is_active = 1;
inline void DependencyMessage::clear_is_active() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_active_ = false;
}
inline bool DependencyMessage::is_active() const {
  // @@protoc_insertion_point(field_get:test.DependencyMessage.is_active)
  return _internal_is_active();
}
inline void DependencyMessage::set_is_active(bool value) {
  _internal_set_is_active(value);
  // @@protoc_insertion_point(field_set:test.DependencyMessage.is_active)
}
inline bool DependencyMessage::_internal_is_active() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_active_;
}
inline void DependencyMessage::_internal_set_is_active(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_active_ = value;
}

// .test.TestMessage test_message = 2;
inline bool DependencyMessage::has_test_message() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.test_message_ != nullptr);
  return value;
}
inline const ::test::TestMessage& DependencyMessage::_internal_test_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::test::TestMessage* p = _impl_.test_message_;
  return p != nullptr ? *p : reinterpret_cast<const ::test::TestMessage&>(::test::_TestMessage_default_instance_);
}
inline const ::test::TestMessage& DependencyMessage::test_message() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:test.DependencyMessage.test_message)
  return _internal_test_message();
}
inline void DependencyMessage::unsafe_arena_set_allocated_test_message(::test::TestMessage* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.test_message_);
  }
  _impl_.test_message_ = reinterpret_cast<::test::TestMessage*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:test.DependencyMessage.test_message)
}
inline ::test::TestMessage* DependencyMessage::release_test_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::test::TestMessage* released = _impl_.test_message_;
  _impl_.test_message_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::test::TestMessage* DependencyMessage::unsafe_arena_release_test_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:test.DependencyMessage.test_message)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::test::TestMessage* temp = _impl_.test_message_;
  _impl_.test_message_ = nullptr;
  return temp;
}
inline ::test::TestMessage* DependencyMessage::_internal_mutable_test_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.test_message_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::test::TestMessage>(GetArena());
    _impl_.test_message_ = reinterpret_cast<::test::TestMessage*>(p);
  }
  return _impl_.test_message_;
}
inline ::test::TestMessage* DependencyMessage::mutable_test_message() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::test::TestMessage* _msg = _internal_mutable_test_message();
  // @@protoc_insertion_point(field_mutable:test.DependencyMessage.test_message)
  return _msg;
}
inline void DependencyMessage::set_allocated_test_message(::test::TestMessage* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.test_message_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.test_message_ = reinterpret_cast<::test::TestMessage*>(value);
  // @@protoc_insertion_point(field_set_allocated:test.DependencyMessage.test_message)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace test


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // test_2fdep_2eproto_2epb_2eh
