// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: test/dep.proto
// Protobuf C++ Version: 5.29.3

#include "test/dep.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace test {

inline constexpr DependencyMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        test_message_{nullptr},
        is_active_{false} {}

template <typename>
PROTOBUF_CONSTEXPR DependencyMessage::DependencyMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DependencyMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DependencyMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DependencyMessageDefaultTypeInternal() {}
  union {
    DependencyMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DependencyMessageDefaultTypeInternal _DependencyMessage_default_instance_;
}  // namespace test
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_test_2fdep_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_test_2fdep_2eproto = nullptr;
const ::uint32_t
    TableStruct_test_2fdep_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::test::DependencyMessage, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::test::DependencyMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::test::DependencyMessage, _impl_.is_active_),
        PROTOBUF_FIELD_OFFSET(::test::DependencyMessage, _impl_.test_message_),
        ~0u,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::test::DependencyMessage)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::test::_DependencyMessage_default_instance_._instance,
};
const char descriptor_table_protodef_test_2fdep_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016test/dep.proto\022\004test\032\017test/test.proto\""
    "O\n\021DependencyMessage\022\021\n\tis_active\030\001 \001(\010\022"
    "\'\n\014test_message\030\002 \001(\0132\021.test.TestMessage"
    "b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_test_2fdep_2eproto_deps[1] =
    {
        &::descriptor_table_test_2ftest_2eproto,
};
static ::absl::once_flag descriptor_table_test_2fdep_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_test_2fdep_2eproto = {
    false,
    false,
    128,
    descriptor_table_protodef_test_2fdep_2eproto,
    "test/dep.proto",
    &descriptor_table_test_2fdep_2eproto_once,
    descriptor_table_test_2fdep_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_test_2fdep_2eproto::offsets,
    file_level_enum_descriptors_test_2fdep_2eproto,
    file_level_service_descriptors_test_2fdep_2eproto,
};
namespace test {
// ===================================================================

class DependencyMessage::_Internal {
 public:
  using HasBits =
      decltype(std::declval<DependencyMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(DependencyMessage, _impl_._has_bits_);
};

void DependencyMessage::clear_test_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.test_message_ != nullptr) _impl_.test_message_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
DependencyMessage::DependencyMessage(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:test.DependencyMessage)
}
inline PROTOBUF_NDEBUG_INLINE DependencyMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::test::DependencyMessage& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

DependencyMessage::DependencyMessage(
    ::google::protobuf::Arena* arena,
    const DependencyMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DependencyMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.test_message_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::test::TestMessage>(
                              arena, *from._impl_.test_message_)
                        : nullptr;
  _impl_.is_active_ = from._impl_.is_active_;

  // @@protoc_insertion_point(copy_constructor:test.DependencyMessage)
}
inline PROTOBUF_NDEBUG_INLINE DependencyMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void DependencyMessage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, test_message_),
           0,
           offsetof(Impl_, is_active_) -
               offsetof(Impl_, test_message_) +
               sizeof(Impl_::is_active_));
}
DependencyMessage::~DependencyMessage() {
  // @@protoc_insertion_point(destructor:test.DependencyMessage)
  SharedDtor(*this);
}
inline void DependencyMessage::SharedDtor(MessageLite& self) {
  DependencyMessage& this_ = static_cast<DependencyMessage&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.test_message_;
  this_._impl_.~Impl_();
}

inline void* DependencyMessage::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) DependencyMessage(arena);
}
constexpr auto DependencyMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(DependencyMessage),
                                            alignof(DependencyMessage));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull DependencyMessage::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_DependencyMessage_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &DependencyMessage::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<DependencyMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &DependencyMessage::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<DependencyMessage>(), &DependencyMessage::ByteSizeLong,
            &DependencyMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(DependencyMessage, _impl_._cached_size_),
        false,
    },
    &DependencyMessage::kDescriptorMethods,
    &descriptor_table_test_2fdep_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* DependencyMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> DependencyMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(DependencyMessage, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::test::DependencyMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .test.TestMessage test_message = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(DependencyMessage, _impl_.test_message_)}},
    // bool is_active = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(DependencyMessage, _impl_.is_active_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(DependencyMessage, _impl_.is_active_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool is_active = 1;
    {PROTOBUF_FIELD_OFFSET(DependencyMessage, _impl_.is_active_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // .test.TestMessage test_message = 2;
    {PROTOBUF_FIELD_OFFSET(DependencyMessage, _impl_.test_message_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::test::TestMessage>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void DependencyMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:test.DependencyMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.test_message_ != nullptr);
    _impl_.test_message_->Clear();
  }
  _impl_.is_active_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* DependencyMessage::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const DependencyMessage& this_ = static_cast<const DependencyMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* DependencyMessage::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const DependencyMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:test.DependencyMessage)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool is_active = 1;
          if (this_._internal_is_active() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_is_active(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .test.TestMessage test_message = 2;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.test_message_, this_._impl_.test_message_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:test.DependencyMessage)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t DependencyMessage::ByteSizeLong(const MessageLite& base) {
          const DependencyMessage& this_ = static_cast<const DependencyMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t DependencyMessage::ByteSizeLong() const {
          const DependencyMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:test.DependencyMessage)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .test.TestMessage test_message = 2;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.test_message_);
            }
          }
           {
            // bool is_active = 1;
            if (this_._internal_is_active() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void DependencyMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DependencyMessage*>(&to_msg);
  auto& from = static_cast<const DependencyMessage&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:test.DependencyMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.test_message_ != nullptr);
    if (_this->_impl_.test_message_ == nullptr) {
      _this->_impl_.test_message_ =
          ::google::protobuf::Message::CopyConstruct<::test::TestMessage>(arena, *from._impl_.test_message_);
    } else {
      _this->_impl_.test_message_->MergeFrom(*from._impl_.test_message_);
    }
  }
  if (from._internal_is_active() != 0) {
    _this->_impl_.is_active_ = from._impl_.is_active_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DependencyMessage::CopyFrom(const DependencyMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:test.DependencyMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DependencyMessage::InternalSwap(DependencyMessage* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DependencyMessage, _impl_.is_active_)
      + sizeof(DependencyMessage::_impl_.is_active_)
      - PROTOBUF_FIELD_OFFSET(DependencyMessage, _impl_.test_message_)>(
          reinterpret_cast<char*>(&_impl_.test_message_),
          reinterpret_cast<char*>(&other->_impl_.test_message_));
}

::google::protobuf::Metadata DependencyMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace test
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_test_2fdep_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
