// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: test/test.proto
// Protobuf C++ Version: 5.29.3

#include "test/test.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace test {

inline constexpr TestMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : test_string_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        test_bytes_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        test_bool_{false},
        test_float_{0},
        test_double_{0},
        test_fixed64_{::uint64_t{0u}},
        test_fixed32_{0u},
        test_int32_{0},
        test_int64_{::int64_t{0}},
        test_sfixed64_{::int64_t{0}},
        test_sfixed32_{0},
        test_sint32_{0},
        test_sint64_{::int64_t{0}},
        test_uint64_{::uint64_t{0u}},
        test_uint32_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TestMessage::TestMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TestMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TestMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TestMessageDefaultTypeInternal() {}
  union {
    TestMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TestMessageDefaultTypeInternal _TestMessage_default_instance_;
}  // namespace test
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_test_2ftest_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_test_2ftest_2eproto = nullptr;
const ::uint32_t
    TableStruct_test_2ftest_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::test::TestMessage, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::test::TestMessage, _impl_.test_string_),
        PROTOBUF_FIELD_OFFSET(::test::TestMessage, _impl_.test_bool_),
        PROTOBUF_FIELD_OFFSET(::test::TestMessage, _impl_.test_bytes_),
        PROTOBUF_FIELD_OFFSET(::test::TestMessage, _impl_.test_double_),
        PROTOBUF_FIELD_OFFSET(::test::TestMessage, _impl_.test_float_),
        PROTOBUF_FIELD_OFFSET(::test::TestMessage, _impl_.test_fixed32_),
        PROTOBUF_FIELD_OFFSET(::test::TestMessage, _impl_.test_fixed64_),
        PROTOBUF_FIELD_OFFSET(::test::TestMessage, _impl_.test_int32_),
        PROTOBUF_FIELD_OFFSET(::test::TestMessage, _impl_.test_int64_),
        PROTOBUF_FIELD_OFFSET(::test::TestMessage, _impl_.test_sfixed32_),
        PROTOBUF_FIELD_OFFSET(::test::TestMessage, _impl_.test_sfixed64_),
        PROTOBUF_FIELD_OFFSET(::test::TestMessage, _impl_.test_sint32_),
        PROTOBUF_FIELD_OFFSET(::test::TestMessage, _impl_.test_sint64_),
        PROTOBUF_FIELD_OFFSET(::test::TestMessage, _impl_.test_uint32_),
        PROTOBUF_FIELD_OFFSET(::test::TestMessage, _impl_.test_uint64_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::test::TestMessage)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::test::_TestMessage_default_instance_._instance,
};
const char descriptor_table_protodef_test_2ftest_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017test/test.proto\022\004test\032 google/protobuf"
    "/descriptor.proto\"\310\002\n\013TestMessage\022\023\n\013tes"
    "t_string\030\001 \001(\t\022\021\n\ttest_bool\030\002 \001(\010\022\022\n\ntes"
    "t_bytes\030\003 \001(\014\022\023\n\013test_double\030\004 \001(\001\022\022\n\nte"
    "st_float\030\005 \001(\002\022\024\n\014test_fixed32\030\006 \001(\007\022\024\n\014"
    "test_fixed64\030\007 \001(\006\022\022\n\ntest_int32\030\010 \001(\005\022\022"
    "\n\ntest_int64\030\t \001(\003\022\025\n\rtest_sfixed32\030\n \001("
    "\017\022\025\n\rtest_sfixed64\030\013 \001(\020\022\023\n\013test_sint32\030"
    "\014 \001(\021\022\023\n\013test_sint64\030\r \001(\022\022\023\n\013test_uint3"
    "2\030\016 \001(\r\022\023\n\013test_uint64\030\017 \001(\004b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_test_2ftest_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::absl::once_flag descriptor_table_test_2ftest_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_test_2ftest_2eproto = {
    false,
    false,
    396,
    descriptor_table_protodef_test_2ftest_2eproto,
    "test/test.proto",
    &descriptor_table_test_2ftest_2eproto_once,
    descriptor_table_test_2ftest_2eproto_deps,
    1,
    1,
    schemas,
    file_default_instances,
    TableStruct_test_2ftest_2eproto::offsets,
    file_level_enum_descriptors_test_2ftest_2eproto,
    file_level_service_descriptors_test_2ftest_2eproto,
};
namespace test {
// ===================================================================

class TestMessage::_Internal {
 public:
};

TestMessage::TestMessage(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:test.TestMessage)
}
inline PROTOBUF_NDEBUG_INLINE TestMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::test::TestMessage& from_msg)
      : test_string_(arena, from.test_string_),
        test_bytes_(arena, from.test_bytes_),
        _cached_size_{0} {}

TestMessage::TestMessage(
    ::google::protobuf::Arena* arena,
    const TestMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TestMessage* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, test_bool_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, test_bool_),
           offsetof(Impl_, test_uint32_) -
               offsetof(Impl_, test_bool_) +
               sizeof(Impl_::test_uint32_));

  // @@protoc_insertion_point(copy_constructor:test.TestMessage)
}
inline PROTOBUF_NDEBUG_INLINE TestMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : test_string_(arena),
        test_bytes_(arena),
        _cached_size_{0} {}

inline void TestMessage::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, test_bool_),
           0,
           offsetof(Impl_, test_uint32_) -
               offsetof(Impl_, test_bool_) +
               sizeof(Impl_::test_uint32_));
}
TestMessage::~TestMessage() {
  // @@protoc_insertion_point(destructor:test.TestMessage)
  SharedDtor(*this);
}
inline void TestMessage::SharedDtor(MessageLite& self) {
  TestMessage& this_ = static_cast<TestMessage&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.test_string_.Destroy();
  this_._impl_.test_bytes_.Destroy();
  this_._impl_.~Impl_();
}

inline void* TestMessage::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TestMessage(arena);
}
constexpr auto TestMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(TestMessage),
                                            alignof(TestMessage));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TestMessage::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TestMessage_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TestMessage::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TestMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TestMessage::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TestMessage>(), &TestMessage::ByteSizeLong,
            &TestMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TestMessage, _impl_._cached_size_),
        false,
    },
    &TestMessage::kDescriptorMethods,
    &descriptor_table_test_2ftest_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TestMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 15, 0, 44, 2> TestMessage::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    15, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294934528,  // skipmap
    offsetof(decltype(_table_), field_entries),
    15,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::test::TestMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string test_string = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_string_)}},
    // bool test_bool = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(TestMessage, _impl_.test_bool_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_bool_)}},
    // bytes test_bytes = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_bytes_)}},
    // double test_double = 4;
    {::_pbi::TcParser::FastF64S1,
     {33, 63, 0, PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_double_)}},
    // float test_float = 5;
    {::_pbi::TcParser::FastF32S1,
     {45, 63, 0, PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_float_)}},
    // fixed32 test_fixed32 = 6;
    {::_pbi::TcParser::FastF32S1,
     {53, 63, 0, PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_fixed32_)}},
    // fixed64 test_fixed64 = 7;
    {::_pbi::TcParser::FastF64S1,
     {57, 63, 0, PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_fixed64_)}},
    // int32 test_int32 = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TestMessage, _impl_.test_int32_), 63>(),
     {64, 63, 0, PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_int32_)}},
    // int64 test_int64 = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(TestMessage, _impl_.test_int64_), 63>(),
     {72, 63, 0, PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_int64_)}},
    // sfixed32 test_sfixed32 = 10;
    {::_pbi::TcParser::FastF32S1,
     {85, 63, 0, PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_sfixed32_)}},
    // sfixed64 test_sfixed64 = 11;
    {::_pbi::TcParser::FastF64S1,
     {89, 63, 0, PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_sfixed64_)}},
    // sint32 test_sint32 = 12;
    {::_pbi::TcParser::FastZ32S1,
     {96, 63, 0, PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_sint32_)}},
    // sint64 test_sint64 = 13;
    {::_pbi::TcParser::FastZ64S1,
     {104, 63, 0, PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_sint64_)}},
    // uint32 test_uint32 = 14;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TestMessage, _impl_.test_uint32_), 63>(),
     {112, 63, 0, PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_uint32_)}},
    // uint64 test_uint64 = 15;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(TestMessage, _impl_.test_uint64_), 63>(),
     {120, 63, 0, PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_uint64_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string test_string = 1;
    {PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_string_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool test_bool = 2;
    {PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_bool_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // bytes test_bytes = 3;
    {PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_bytes_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // double test_double = 4;
    {PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_double_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // float test_float = 5;
    {PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_float_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // fixed32 test_fixed32 = 6;
    {PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_fixed32_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFixed32)},
    // fixed64 test_fixed64 = 7;
    {PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_fixed64_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFixed64)},
    // int32 test_int32 = 8;
    {PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_int32_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int64 test_int64 = 9;
    {PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_int64_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // sfixed32 test_sfixed32 = 10;
    {PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_sfixed32_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kSFixed32)},
    // sfixed64 test_sfixed64 = 11;
    {PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_sfixed64_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kSFixed64)},
    // sint32 test_sint32 = 12;
    {PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_sint32_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kSInt32)},
    // sint64 test_sint64 = 13;
    {PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_sint64_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kSInt64)},
    // uint32 test_uint32 = 14;
    {PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_uint32_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint64 test_uint64 = 15;
    {PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_uint64_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
    "\20\13\0\0\0\0\0\0\0\0\0\0\0\0\0\0"
    "test.TestMessage"
    "test_string"
  }},
};

PROTOBUF_NOINLINE void TestMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:test.TestMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.test_string_.ClearToEmpty();
  _impl_.test_bytes_.ClearToEmpty();
  ::memset(&_impl_.test_bool_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.test_uint32_) -
      reinterpret_cast<char*>(&_impl_.test_bool_)) + sizeof(_impl_.test_uint32_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TestMessage::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TestMessage& this_ = static_cast<const TestMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TestMessage::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TestMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:test.TestMessage)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string test_string = 1;
          if (!this_._internal_test_string().empty()) {
            const std::string& _s = this_._internal_test_string();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "test.TestMessage.test_string");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // bool test_bool = 2;
          if (this_._internal_test_bool() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_test_bool(), target);
          }

          // bytes test_bytes = 3;
          if (!this_._internal_test_bytes().empty()) {
            const std::string& _s = this_._internal_test_bytes();
            target = stream->WriteBytesMaybeAliased(3, _s, target);
          }

          // double test_double = 4;
          if (::absl::bit_cast<::uint64_t>(this_._internal_test_double()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                4, this_._internal_test_double(), target);
          }

          // float test_float = 5;
          if (::absl::bit_cast<::uint32_t>(this_._internal_test_float()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                5, this_._internal_test_float(), target);
          }

          // fixed32 test_fixed32 = 6;
          if (this_._internal_test_fixed32() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFixed32ToArray(
                6, this_._internal_test_fixed32(), target);
          }

          // fixed64 test_fixed64 = 7;
          if (this_._internal_test_fixed64() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFixed64ToArray(
                7, this_._internal_test_fixed64(), target);
          }

          // int32 test_int32 = 8;
          if (this_._internal_test_int32() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<8>(
                    stream, this_._internal_test_int32(), target);
          }

          // int64 test_int64 = 9;
          if (this_._internal_test_int64() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<9>(
                    stream, this_._internal_test_int64(), target);
          }

          // sfixed32 test_sfixed32 = 10;
          if (this_._internal_test_sfixed32() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteSFixed32ToArray(
                10, this_._internal_test_sfixed32(), target);
          }

          // sfixed64 test_sfixed64 = 11;
          if (this_._internal_test_sfixed64() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteSFixed64ToArray(
                11, this_._internal_test_sfixed64(), target);
          }

          // sint32 test_sint32 = 12;
          if (this_._internal_test_sint32() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteSInt32ToArray(
                12, this_._internal_test_sint32(), target);
          }

          // sint64 test_sint64 = 13;
          if (this_._internal_test_sint64() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteSInt64ToArray(
                13, this_._internal_test_sint64(), target);
          }

          // uint32 test_uint32 = 14;
          if (this_._internal_test_uint32() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                14, this_._internal_test_uint32(), target);
          }

          // uint64 test_uint64 = 15;
          if (this_._internal_test_uint64() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                15, this_._internal_test_uint64(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:test.TestMessage)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TestMessage::ByteSizeLong(const MessageLite& base) {
          const TestMessage& this_ = static_cast<const TestMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TestMessage::ByteSizeLong() const {
          const TestMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:test.TestMessage)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string test_string = 1;
            if (!this_._internal_test_string().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_test_string());
            }
            // bytes test_bytes = 3;
            if (!this_._internal_test_bytes().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                              this_._internal_test_bytes());
            }
            // bool test_bool = 2;
            if (this_._internal_test_bool() != 0) {
              total_size += 2;
            }
            // float test_float = 5;
            if (::absl::bit_cast<::uint32_t>(this_._internal_test_float()) != 0) {
              total_size += 5;
            }
            // double test_double = 4;
            if (::absl::bit_cast<::uint64_t>(this_._internal_test_double()) != 0) {
              total_size += 9;
            }
            // fixed64 test_fixed64 = 7;
            if (this_._internal_test_fixed64() != 0) {
              total_size += 9;
            }
            // fixed32 test_fixed32 = 6;
            if (this_._internal_test_fixed32() != 0) {
              total_size += 5;
            }
            // int32 test_int32 = 8;
            if (this_._internal_test_int32() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_test_int32());
            }
            // int64 test_int64 = 9;
            if (this_._internal_test_int64() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_test_int64());
            }
            // sfixed64 test_sfixed64 = 11;
            if (this_._internal_test_sfixed64() != 0) {
              total_size += 9;
            }
            // sfixed32 test_sfixed32 = 10;
            if (this_._internal_test_sfixed32() != 0) {
              total_size += 5;
            }
            // sint32 test_sint32 = 12;
            if (this_._internal_test_sint32() != 0) {
              total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(
                  this_._internal_test_sint32());
            }
            // sint64 test_sint64 = 13;
            if (this_._internal_test_sint64() != 0) {
              total_size += ::_pbi::WireFormatLite::SInt64SizePlusOne(
                  this_._internal_test_sint64());
            }
            // uint64 test_uint64 = 15;
            if (this_._internal_test_uint64() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_test_uint64());
            }
            // uint32 test_uint32 = 14;
            if (this_._internal_test_uint32() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_test_uint32());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TestMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TestMessage*>(&to_msg);
  auto& from = static_cast<const TestMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:test.TestMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_test_string().empty()) {
    _this->_internal_set_test_string(from._internal_test_string());
  }
  if (!from._internal_test_bytes().empty()) {
    _this->_internal_set_test_bytes(from._internal_test_bytes());
  }
  if (from._internal_test_bool() != 0) {
    _this->_impl_.test_bool_ = from._impl_.test_bool_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_test_float()) != 0) {
    _this->_impl_.test_float_ = from._impl_.test_float_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_test_double()) != 0) {
    _this->_impl_.test_double_ = from._impl_.test_double_;
  }
  if (from._internal_test_fixed64() != 0) {
    _this->_impl_.test_fixed64_ = from._impl_.test_fixed64_;
  }
  if (from._internal_test_fixed32() != 0) {
    _this->_impl_.test_fixed32_ = from._impl_.test_fixed32_;
  }
  if (from._internal_test_int32() != 0) {
    _this->_impl_.test_int32_ = from._impl_.test_int32_;
  }
  if (from._internal_test_int64() != 0) {
    _this->_impl_.test_int64_ = from._impl_.test_int64_;
  }
  if (from._internal_test_sfixed64() != 0) {
    _this->_impl_.test_sfixed64_ = from._impl_.test_sfixed64_;
  }
  if (from._internal_test_sfixed32() != 0) {
    _this->_impl_.test_sfixed32_ = from._impl_.test_sfixed32_;
  }
  if (from._internal_test_sint32() != 0) {
    _this->_impl_.test_sint32_ = from._impl_.test_sint32_;
  }
  if (from._internal_test_sint64() != 0) {
    _this->_impl_.test_sint64_ = from._impl_.test_sint64_;
  }
  if (from._internal_test_uint64() != 0) {
    _this->_impl_.test_uint64_ = from._impl_.test_uint64_;
  }
  if (from._internal_test_uint32() != 0) {
    _this->_impl_.test_uint32_ = from._impl_.test_uint32_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TestMessage::CopyFrom(const TestMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:test.TestMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TestMessage::InternalSwap(TestMessage* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.test_string_, &other->_impl_.test_string_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.test_bytes_, &other->_impl_.test_bytes_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_uint32_)
      + sizeof(TestMessage::_impl_.test_uint32_)
      - PROTOBUF_FIELD_OFFSET(TestMessage, _impl_.test_bool_)>(
          reinterpret_cast<char*>(&_impl_.test_bool_),
          reinterpret_cast<char*>(&other->_impl_.test_bool_));
}

::google::protobuf::Metadata TestMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace test
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_test_2ftest_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
