/**
 * Confluent Schema Registry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.13.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "srclient/rest/ClientConfiguration.h"

namespace org {
namespace openapitools {
namespace client {
namespace api {

ClientConfiguration::ClientConfiguration(const std::vector<std::string>& baseUrls)
    : m_BaseUrls(baseUrls)
{
}

ClientConfiguration::~ClientConfiguration()
{
}

std::vector<std::string> ClientConfiguration::getBaseUrls() const
{
    return m_BaseUrls;
}

}
}
}
}
