/**
 * Confluent Schema Registry
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.13.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "srclient/rest/RestException.h"

namespace org {
namespace openapitools {
namespace client {
namespace api {

RestException::RestException( int errorCode
    , const std::string& message
    , std::shared_ptr<std::istream> content /*= nullptr*/ )
    : m_Content(content)
{
}

RestException::~RestException()
{
}

std::shared_ptr<std::istream> RestException::getContent() const
{
    return m_Content;
}

}
}
}
}
